### ISSUE TITLE
Rename "hySpc.skeleton" into "pkg-skeleton"

### ISSUE THREAD

**Issue by GegznaV** [eoduniyi/hyperSpec.skeleton#15]
I suggest leaving `hySpc` pattern for packages only and renaming other non-package repositories.

`hySpc.skeleton` sould be renamed into, e.g., `pkg-skeleton`.

**Comment by eoduniyi** [comment]
@GegznaV I don't have the permissions to access the settings on the repo anymore. Not sure what happened. I did try and fork the project and then renamed it from my account, but transferring did not work because there was "already a `hySpc.skeleton` in the `r-hyperspec` network"...So I think @cbeleites would know best.

**Comment by GegznaV** [comment]
Yes, let's wait until Claudia has time for this.

**Comment by cbeleites** [comment]
Done
