### ISSUE TITLE
Why is MIT license is used instead of GPL-3?

### ISSUE THREAD

**Issue by GegznaV** [eoduniyi/hyperSpec.skeleton#8]

**Comment by cbeleites** [comment]
This is a good point. I'll put license discussion into the agenda for one of the upcoming Monday video conferences.

---

**hyperSpec** is under GPL since it was first published. This turned out to scare away some potential users:

Some years ago I was contacted by a company who wanted to use **hyperSpec**. They thought that for using **hyperSpec** in their work they need a less restrictive license than GPL (more precisely: a license that is not copyleft). While from what they told me about the intended use I think they'd have been fine with `library(hyperSpec)` under GPL (according to [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.html)), they were afraid of possible legal entanglements and in consequence decided not to use **hyperSpec**.  

In general, publishing a package such as **hyperSpec** under GPL leaves the possibility to the owner of the copyright to license it in parallel under a less restrictive license if that is required. But this possibility does not exist for **hyperSpec** since all contributors always contributed to the GPL version, i.e. AFAIK we'd have to get separate permission to re-license from every single contriubutor, and for legislations like Germany their employers, respectively. This is infeasible.

So for the new packages, I'd like to either directly go for a less "scary" license, or to provide a feasible way to re-license for such potential users. While in theory, I'd prefer the latter, I don't know how to do this in a feasible and legally reliable way.

**Comment by bryanhanson** [comment]
Some possibly useful discussions:

* https://opensource.stackexchange.com/q/9805
* https://opensource.stackexchange.com/q/7562
* https://opensource.stackexchange.com/q/9587
* https://opensource.stackexchange.com/q/8181 Raises the issue of copyrighted code and trademarked brands (apparently people both open source license and claim copyright).

From what I can gather, with GPL-3 there are no limitations on a commercial entity taking up a project and adding to it, as long as it is used in house only and not distributed.  Not sure if this is case Claudia was thinking about.

**Comment by ximeg** [comment]
I am in favor of more permissive licenses like MIT. 'Copyleft' licenses are very restrictive and can frighten away a reasonable fraction of potential users, including potential contributors.

**Comment by cbeleites** [comment]
@GegznaV I'll leave the issue open so we're reminded that you also need to have your say when you are back.

**Comment by cbeleites** [comment]
@bryanhanson, @eoduniyi, @ximeg, @GegznaV  : would you agree to re-license also **hyperSpec** itself with a more permissive license iff that should ever become feasible?

**Comment by GegznaV** [comment]
I agree if MIT license is used for the whole `hyperSpec` family or separate packages. 

But the question is whether it is legal to change the licence
from GPL into MIT. As I understand, all derivatives (including new
packages) of the code under GPL should also be under the same licence.

---

And why I paid attention to this? Because information in CONTRIBUTION.md
mentions only GPL. And I understand that CONTRIBUTION.md file is common for
the whole family of hyperSpec packages.

2020 birž. 29, pr 21:57, Claudia Beleites <notifications@github.com> rašė:

**Comment by bryanhanson** [comment]
Fine with me.

**Comment by cbeleites** [comment]
@GegznaV you are right that we need to be careful and that GPL itself does not allow to change the license to MIT. 
It is possible, however, for the owner of the copyright to grant another license, e.g. MIT: GPL is not exclusive. 

For old code in  **hySpc.testthat** and **hySpc.read.Witec** where the copyright is owned by me, I can grant a new MIT license (in addition to the GPL). To make this explicit: I hereby re-license all code in the **hyperSpec** project where I hold the copyright and permit the **hyperSpec** project to license this code under GPL-3 as well as under under MIT. 

We will have to be careful to sort out who owns the copyright for which parts of the code.

I updated the contributions guide accordingly.

**Comment by ximeg** [comment]
> @bryanhanson, @eoduniyi, @ximeg, @GegznaV : would you agree to re-license also **hyperSpec** itself with a more permissive license iff that should ever become feasible?

That's fine with me, do whatever you need/want with the code that I've contributed! :)

**Comment by GegznaV** [comment]
@cbeleites And who is the copyright owner of the **hyperSpec** package?
And how did you decide, that code in, e.g.,  **hySpc.read.Witec**, could be relicensed and some other lines of code cannot?
Do different lines of code in a package have different copyright holders? Those legal things are a bit vague to me.

**Comment by eoduniyi** [comment]
Hmm so @cbeleites basically **MIT LICENSE** _eats_ **GPL LICENSE** => files created via **GPL** stay under **GPL** regardless if the entire project is under **MIT** or not?

**Comment by cbeleites** [comment]
@GegznaV : yes, parts of a project can have different copyright holders. 

@eoduniyi: 

- files which were contributed to be included under GPL stay GPL until we get them re-licensed (by the original copyright holder: they can grant further licenses).
- But GPL "eats" MIT (it is "contagious"): we can have files under MIT in a GPL project, but the project will put them automatically also under GPL.
