### ISSUE TITLE
Add necessary `usethis` commands for the things we cannot set correctly in advance

### ISSUE THREAD

**Issue by GegznaV** [eoduniyi/hyperSpec.skeleton#9]
In the skeleton's README, we could write a sequence of `usethis` or other (e.g., custom-made) commands, that help to set up the aspects of the package we do not know in advance. E.g., commands that add necessary badges, type of license, etc. There are functions that do the most of the job to set up Travis CI and Appveyor (this means that not only plain text files are created by those functions), etc.

 I think the skeleton should contain only those elements of the package that work out of the box (E.g., GitHub Actions workflows, some examples of vignettes, and functions). And all the infrastructure should work in the skeleton: CI, code coverage, **pkgdown** builds, etc.

**Comment by eoduniyi** [comment]
Sounds good to me!

**Comment by cbeleites** [comment]
I agree for the badges, but I'm not convinced the skeleton should actually *work* on CI: the errors we get now are useful since they point to required changes e.g. in the `DESCRIPTION` file. Putting something like "SKELETON" there would make CI builds run, but that would then mean an additional risk of not changing all the things that need to be customized.

**Comment by cbeleites** [comment]
We decided for now to stay with the skeleton package rather than moving over to **usethis** - with the exception of **usethis** commands that do not need further changes for us. 

The skeleton should stay with not filled in fields leading to the builds fail in order to make sure the fields will be correctly set for derived packages.
